/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package strategypattern.Presentation;

import java.awt.Component;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JPanel;
import javax.swing.JTextField;
import strategypattern.Abstraction.Clock;
import strategypattern.Abstraction.SoundControl;
import strategypattern.Abstraction.SoundOffCommand;
import strategypattern.Abstraction.SoundOnCommand;
import strategypattern.Control.ClockControl;

/**
 *
 * @author rebirth
 */
public class ClockPresentation extends javax.swing.JFrame {
    SoundControl soundControl = new SoundControl();
    ClockControl clockControl1;

    /**
     * Creates new form NewJFrame
     */
    public ClockPresentation() {
        this.clockControl1 = new ClockControl(this);
        
        initComponents();
    }
    
    public void drawClock(JPanel Analoog, JPanel Digitaal) {
        clockOnePanel.removeAll();
        clockTwoPanel.removeAll();
        clockOnePanel.add(Analoog);
        clockTwoPanel.add(Digitaal);
        Analoog.setVisible(false);
        Digitaal.setVisible(false);
        Analoog.setVisible(true);
        Digitaal.setVisible(true);
        Analoog.repaint();
        Digitaal.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displaySettingsGroup = new javax.swing.ButtonGroup();
        soundSettingsGroup = new javax.swing.ButtonGroup();
        uTC1 = new strategypattern.Abstraction.UTC();
        timeZoneGroup1 = new javax.swing.ButtonGroup();
        timeZoneGroup2 = new javax.swing.ButtonGroup();
        timeZoneGroup3 = new javax.swing.ButtonGroup();
        clockOnePanel = new javax.swing.JPanel();
        SoundSettings = new javax.swing.JPanel();
        noSoundButton = new javax.swing.JRadioButton();
        tickSoundButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        displaySettings1 = new javax.swing.JPanel();
        enebleUTC = new javax.swing.JRadioButton();
        enebleMET = new javax.swing.JRadioButton();
        enebleEST = new javax.swing.JRadioButton();
        clockTwoPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clockOnePanel.setBackground(new java.awt.Color(204, 204, 204));
        clockOnePanel.setLayout(new java.awt.GridLayout(1, 0));

        SoundSettings.setBackground(new java.awt.Color(204, 204, 204));

        soundSettingsGroup.add(noSoundButton);
        noSoundButton.setSelected(true);
        noSoundButton.setText("None");
        noSoundButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noSoundButtonMouseClicked(evt);
            }
        });
        noSoundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noSoundButtonActionPerformed(evt);
            }
        });

        soundSettingsGroup.add(tickSoundButton);
        tickSoundButton.setText("Tick");
        tickSoundButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tickSoundButtonMouseClicked(evt);
            }
        });

        jLabel2.setText("Sound");

        javax.swing.GroupLayout SoundSettingsLayout = new javax.swing.GroupLayout(SoundSettings);
        SoundSettings.setLayout(SoundSettingsLayout);
        SoundSettingsLayout.setHorizontalGroup(
            SoundSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SoundSettingsLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(SoundSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tickSoundButton)
                    .addComponent(noSoundButton))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        SoundSettingsLayout.setVerticalGroup(
            SoundSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SoundSettingsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noSoundButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tickSoundButton)
                .addGap(27, 27, 27))
        );

        displaySettings1.setBackground(new java.awt.Color(204, 204, 204));

        timeZoneGroup1.add(enebleUTC);
        enebleUTC.setSelected(true);
        enebleUTC.setText("UTC");
        enebleUTC.setToolTipText("");
        enebleUTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enebleUTCActionPerformed(evt);
            }
        });

        timeZoneGroup1.add(enebleMET);
        enebleMET.setText("MET");
        enebleMET.setToolTipText("");
        enebleMET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enebleMETActionPerformed(evt);
            }
        });

        timeZoneGroup1.add(enebleEST);
        enebleEST.setText("EST");
        enebleEST.setToolTipText("");
        enebleEST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enebleESTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout displaySettings1Layout = new javax.swing.GroupLayout(displaySettings1);
        displaySettings1.setLayout(displaySettings1Layout);
        displaySettings1Layout.setHorizontalGroup(
            displaySettings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displaySettings1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(displaySettings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enebleEST)
                    .addGroup(displaySettings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(enebleMET)
                        .addComponent(enebleUTC)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        displaySettings1Layout.setVerticalGroup(
            displaySettings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displaySettings1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(enebleUTC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enebleMET)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enebleEST)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        enebleUTC.getAccessibleContext().setAccessibleName("enebleUTC");

        clockTwoPanel.setBackground(new java.awt.Color(204, 204, 204));
        clockTwoPanel.setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clockOnePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displaySettings1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clockTwoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SoundSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clockOnePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(clockTwoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displaySettings1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SoundSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noSoundButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noSoundButtonMouseClicked
        SoundOffCommand soundOff = new SoundOffCommand(clockControl1);
        soundControl.setCommand(soundOff);
        soundControl.buttonWasPressed();

    }//GEN-LAST:event_noSoundButtonMouseClicked

    private void tickSoundButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tickSoundButtonMouseClicked
        SoundOnCommand soundOn = new SoundOnCommand(clockControl1);
        soundControl.setCommand(soundOn);
        soundControl.buttonWasPressed();
    }//GEN-LAST:event_tickSoundButtonMouseClicked

    private void enebleUTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enebleUTCActionPerformed
        clockControl1.setUTC();
    }//GEN-LAST:event_enebleUTCActionPerformed

    private void enebleMETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enebleMETActionPerformed
        clockControl1.setMET();
    }//GEN-LAST:event_enebleMETActionPerformed

    private void enebleESTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enebleESTActionPerformed
        clockControl1.setEST();
    }//GEN-LAST:event_enebleESTActionPerformed

    private void noSoundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noSoundButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noSoundButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SoundSettings;
    private javax.swing.JPanel clockOnePanel;
    private javax.swing.JPanel clockTwoPanel;
    private javax.swing.JPanel displaySettings1;
    private javax.swing.ButtonGroup displaySettingsGroup;
    private javax.swing.JRadioButton enebleEST;
    private javax.swing.JRadioButton enebleMET;
    private javax.swing.JRadioButton enebleUTC;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton noSoundButton;
    private javax.swing.ButtonGroup soundSettingsGroup;
    private javax.swing.JRadioButton tickSoundButton;
    private javax.swing.ButtonGroup timeZoneGroup1;
    private javax.swing.ButtonGroup timeZoneGroup2;
    private javax.swing.ButtonGroup timeZoneGroup3;
    private strategypattern.Abstraction.UTC uTC1;
    // End of variables declaration//GEN-END:variables
}
